// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AccountAdd extends Table {
  public static AccountAdd getRootAsAccountAdd(ByteBuffer _bb) { return getRootAsAccountAdd(_bb, new AccountAdd()); }
  public static AccountAdd getRootAsAccountAdd(ByteBuffer _bb, AccountAdd obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AccountAdd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int account(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int accountLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer accountAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public iroha.Account AccountAsIroha() { return AccountAsIroha(new iroha.Account()); }
  public iroha.Account AccountAsIroha(iroha.Account obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o)), bb) : null; }

  public static int createAccountAdd(FlatBufferBuilder builder,
      int accountOffset) {
    builder.startObject(1);
    AccountAdd.addAccount(builder, accountOffset);
    return AccountAdd.endAccountAdd(builder);
  }

  public static void startAccountAdd(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addAccount(FlatBufferBuilder builder, int accountOffset) { builder.addOffset(0, accountOffset, 0); }
  public static int createAccountVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startAccountVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endAccountAdd(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // account
    return o;
  }
}

