// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

public final class AnyAsset {
  private AnyAsset() { }
  public static final byte NONE = 0;
  public static final byte ComplexAsset = 1;
  public static final byte Currency = 2;

  public static final String[] names = { "NONE", "ComplexAsset", "Currency", };

  public static String name(int e) { return names[e]; }
}

