// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AssetTransfer extends Table {
  public static AssetTransfer getRootAsAssetTransfer(ByteBuffer _bb) { return getRootAsAssetTransfer(_bb, new AssetTransfer()); }
  public static AssetTransfer getRootAsAssetTransfer(ByteBuffer _bb, AssetTransfer obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AssetTransfer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int asset(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int assetLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer assetAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public iroha.Asset AssetAsIroha() { return AssetAsIroha(new iroha.Asset()); }
  public iroha.Asset AssetAsIroha(iroha.Asset obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o)), bb) : null; }
  public String sender() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer senderAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String receiver() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer receiverAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createAssetTransfer(FlatBufferBuilder builder,
      int assetOffset,
      int senderOffset,
      int receiverOffset) {
    builder.startObject(3);
    AssetTransfer.addReceiver(builder, receiverOffset);
    AssetTransfer.addSender(builder, senderOffset);
    AssetTransfer.addAsset(builder, assetOffset);
    return AssetTransfer.endAssetTransfer(builder);
  }

  public static void startAssetTransfer(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addAsset(FlatBufferBuilder builder, int assetOffset) { builder.addOffset(0, assetOffset, 0); }
  public static int createAssetVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startAssetVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addSender(FlatBufferBuilder builder, int senderOffset) { builder.addOffset(1, senderOffset, 0); }
  public static void addReceiver(FlatBufferBuilder builder, int receiverOffset) { builder.addOffset(2, receiverOffset, 0); }
  public static int endAssetTransfer(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // asset
    builder.required(o, 6);  // sender
    builder.required(o, 8);  // receiver
    return o;
  }
}

