// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AssetCreate extends Table {
  public static AssetCreate getRootAsAssetCreate(ByteBuffer _bb) { return getRootAsAssetCreate(_bb, new AssetCreate()); }
  public static AssetCreate getRootAsAssetCreate(ByteBuffer _bb, AssetCreate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AssetCreate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String assetName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer assetNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String domainName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer domainNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String ledgerName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ledgerNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String creatorPubKey() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer creatorPubKeyAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }

  public static int createAssetCreate(FlatBufferBuilder builder,
      int asset_nameOffset,
      int domain_nameOffset,
      int ledger_nameOffset,
      int creatorPubKeyOffset) {
    builder.startObject(4);
    AssetCreate.addCreatorPubKey(builder, creatorPubKeyOffset);
    AssetCreate.addLedgerName(builder, ledger_nameOffset);
    AssetCreate.addDomainName(builder, domain_nameOffset);
    AssetCreate.addAssetName(builder, asset_nameOffset);
    return AssetCreate.endAssetCreate(builder);
  }

  public static void startAssetCreate(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addAssetName(FlatBufferBuilder builder, int assetNameOffset) { builder.addOffset(0, assetNameOffset, 0); }
  public static void addDomainName(FlatBufferBuilder builder, int domainNameOffset) { builder.addOffset(1, domainNameOffset, 0); }
  public static void addLedgerName(FlatBufferBuilder builder, int ledgerNameOffset) { builder.addOffset(2, ledgerNameOffset, 0); }
  public static void addCreatorPubKey(FlatBufferBuilder builder, int creatorPubKeyOffset) { builder.addOffset(3, creatorPubKeyOffset, 0); }
  public static int endAssetCreate(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // asset_name
    builder.required(o, 6);  // domain_name
    builder.required(o, 8);  // ledger_name
    builder.required(o, 10);  // creatorPubKey
    return o;
  }
}

