// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

public final class Code {
  private Code() { }
  public static final byte COMMIT = 0;
  public static final byte UNDECIDED = 1;
  public static final byte FAIL = 2;

  public static final String[] names = { "COMMIT", "UNDECIDED", "FAIL", };

  public static String name(int e) { return names[e]; }
}

