// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

public final class Command {
  private Command() { }
  public static final byte NONE = 0;
  public static final byte AssetCreate = 1;
  public static final byte AssetAdd = 2;
  public static final byte AssetRemove = 3;
  public static final byte AssetTransfer = 4;
  public static final byte PeerAdd = 5;
  public static final byte PeerRemove = 6;
  public static final byte PeerSetActive = 7;
  public static final byte PeerSetTrust = 8;
  public static final byte PeerChangeTrust = 9;
  public static final byte AccountAdd = 10;
  public static final byte AccountRemove = 11;
  public static final byte AccountAddSignatory = 12;
  public static final byte AccountRemoveSignatory = 13;
  public static final byte AccountSetUseKeys = 14;
  public static final byte ChaincodeAdd = 15;
  public static final byte ChaincodeRemove = 16;
  public static final byte ChaincodeExecute = 17;

  public static final String[] names = { "NONE", "AssetCreate", "AssetAdd", "AssetRemove", "AssetTransfer", "PeerAdd", "PeerRemove", "PeerSetActive", "PeerSetTrust", "PeerChangeTrust", "AccountAdd", "AccountRemove", "AccountAddSignatory", "AccountRemoveSignatory", "AccountSetUseKeys", "ChaincodeAdd", "ChaincodeRemove", "ChaincodeExecute", };

  public static String name(int e) { return names[e]; }
}

