// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

public final class KeyAlgorithm {
  private KeyAlgorithm() { }
  public static final byte ed25519 = 0;

  public static final String[] names = { "ed25519", };

  public static String name(int e) { return names[e]; }
}

