// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PeerSetTrust extends Table {
  public static PeerSetTrust getRootAsPeerSetTrust(ByteBuffer _bb) { return getRootAsPeerSetTrust(_bb, new PeerSetTrust()); }
  public static PeerSetTrust getRootAsPeerSetTrust(ByteBuffer _bb, PeerSetTrust obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PeerSetTrust __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String peerPubKey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer peerPubKeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public double trust() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createPeerSetTrust(FlatBufferBuilder builder,
      int peerPubKeyOffset,
      double trust) {
    builder.startObject(2);
    PeerSetTrust.addTrust(builder, trust);
    PeerSetTrust.addPeerPubKey(builder, peerPubKeyOffset);
    return PeerSetTrust.endPeerSetTrust(builder);
  }

  public static void startPeerSetTrust(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addPeerPubKey(FlatBufferBuilder builder, int peerPubKeyOffset) { builder.addOffset(0, peerPubKeyOffset, 0); }
  public static void addTrust(FlatBufferBuilder builder, double trust) { builder.addDouble(1, trust, 0.0); }
  public static int endPeerSetTrust(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // peerPubKey
    return o;
  }
}

