// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

public final class ProgrammingLanguage {
  private ProgrammingLanguage() { }
  public static final byte Java8 = 0;

  public static final String[] names = { "Java8", };

  public static String name(int e) { return names[e]; }
}

