// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PublicKey extends Table {
  public static PublicKey getRootAsPublicKey(ByteBuffer _bb) { return getRootAsPublicKey(_bb, new PublicKey()); }
  public static PublicKey getRootAsPublicKey(ByteBuffer _bb, PublicKey obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PublicKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte algorithm() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int data(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int dataLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer dataAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createPublicKey(FlatBufferBuilder builder,
      byte algorithm,
      int dataOffset) {
    builder.startObject(2);
    PublicKey.addData(builder, dataOffset);
    PublicKey.addAlgorithm(builder, algorithm);
    return PublicKey.endPublicKey(builder);
  }

  public static void startPublicKey(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addAlgorithm(FlatBufferBuilder builder, byte algorithm) { builder.addByte(0, algorithm, 0); }
  public static void addData(FlatBufferBuilder builder, int dataOffset) { builder.addOffset(1, dataOffset, 0); }
  public static int createDataVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startDataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endPublicKey(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 6);  // data
    return o;
  }
}

