// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TransactionResponse extends Table {
  public static TransactionResponse getRootAsTransactionResponse(ByteBuffer _bb) { return getRootAsTransactionResponse(_bb, new TransactionResponse()); }
  public static TransactionResponse getRootAsTransactionResponse(ByteBuffer _bb, TransactionResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TransactionResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String message() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public int code() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public iroha.Transaction transaction() { return transaction(new iroha.Transaction()); }
  public iroha.Transaction transaction(iroha.Transaction obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createTransactionResponse(FlatBufferBuilder builder,
      int messageOffset,
      int code,
      int transactionOffset) {
    builder.startObject(3);
    TransactionResponse.addTransaction(builder, transactionOffset);
    TransactionResponse.addMessage(builder, messageOffset);
    TransactionResponse.addCode(builder, code);
    return TransactionResponse.endTransactionResponse(builder);
  }

  public static void startTransactionResponse(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(0, messageOffset, 0); }
  public static void addCode(FlatBufferBuilder builder, int code) { builder.addByte(1, (byte)code, (byte)0); }
  public static void addTransaction(FlatBufferBuilder builder, int transactionOffset) { builder.addOffset(2, transactionOffset, 0); }
  public static int endTransactionResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

