// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

public final class UserPermission {
  private UserPermission() { }
  public static final byte NONE = 0;
  public static final byte UserPermissionRoot = 1;
  public static final byte UserPermissionLedger = 2;
  public static final byte UserPermissionDomain = 3;
  public static final byte UserPermissionAsset = 4;

  public static final String[] names = { "NONE", "UserPermissionRoot", "UserPermissionLedger", "UserPermissionDomain", "UserPermissionAsset", };

  public static String name(int e) { return names[e]; }
}

