// automatically generated by the FlatBuffers compiler, do not modify

package iroha;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserPermissionRoot extends Table {
  public static UserPermissionRoot getRootAsUserPermissionRoot(ByteBuffer _bb) { return getRootAsUserPermissionRoot(_bb, new UserPermissionRoot()); }
  public static UserPermissionRoot getRootAsUserPermissionRoot(ByteBuffer _bb, UserPermissionRoot obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public UserPermissionRoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean ledgerAdd() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean ledgerRemove() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createUserPermissionRoot(FlatBufferBuilder builder,
      boolean ledger_add,
      boolean ledger_remove) {
    builder.startObject(2);
    UserPermissionRoot.addLedgerRemove(builder, ledger_remove);
    UserPermissionRoot.addLedgerAdd(builder, ledger_add);
    return UserPermissionRoot.endUserPermissionRoot(builder);
  }

  public static void startUserPermissionRoot(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addLedgerAdd(FlatBufferBuilder builder, boolean ledgerAdd) { builder.addBoolean(0, ledgerAdd, false); }
  public static void addLedgerRemove(FlatBufferBuilder builder, boolean ledgerRemove) { builder.addBoolean(1, ledgerRemove, false); }
  public static int endUserPermissionRoot(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

